shellchecked all scripts

diff --git a/stage1 b/stage1
--- a/stage1
+++ b/stage1
@@ -4,19 +4,19 @@
 # send a tar archive of these images to stdout
 #
 
-if [ -t 0 -o -t 1 ]; then
+if [ -t 0 ] || [ -t 1 ]; then
 	echo "error: stdin or stdout is a terminal. aborting." 1>&2
 	exit 1
 fi
 
 TMPDIR=$(mktemp -d)
-if [ $? -ne 0 -o ! -d "$TMPDIR" ]; then
+if [ $? -ne 0 ] || [ ! -d "$TMPDIR" ]; then
 	echo "error: could not create temp dir. aborting." 1>&2
 	exit 1
 fi
 
 INFILE=$(mktemp)
-cat - > $INFILE
+cat - > "$INFILE"
 
 #echo "debug: converting with LibreOffice..." 1>&2
 #libreoffice --headless --safe-mode --convert-to pdf --outdir $TMPDIR/ $INFILE 1>&2
@@ -28,13 +28,18 @@ echo "debug: using raw input PDF..." 1>&2
 cp -- "$INFILE" "$TMPDIR/input.pdf"
 
 echo "debug: converting from PDF to PPM..." 1>&2
-pdftoppm $TMPDIR/*.pdf $TMPDIR/page
+pdftoppm "$TMPDIR"/*.pdf "$TMPDIR"/page
 
 #ls -Fla $TMPDIR/* 1>&2
 
-cd $TMPDIR
+# shellcheck disable=SC2164
+cd -- "$TMPDIR"
+if [ $? -ne 0 ]; then
+	echo "error: could not change directory to TMPDIR. aborting." 1>&2
+	exit 1
+fi
+
 echo "debug: tarring PPM files..." 1>&2
-#tar -cf a.tar stage2.d/page-*.ppm
 tar -c page-*.ppm
 if [ $? -ne 0 ]; then
 	echo "error: could not create tar." 1>&2
diff --git a/stage2 b/stage2
--- a/stage2
+++ b/stage2
@@ -1,4 +1,4 @@
-#!/bin/sh
+#!/bin/bash
 #
 # convert images back to PDF with optional OCR:
 #
@@ -18,7 +18,7 @@ if [ -t 1 ]; then
 fi
 
 TMPDIR=$(mktemp -d)
-if [ $? -ne 0 -o ! -d "$TMPDIR" ]; then
+if [ $? -ne 0 ] || [ ! -d "$TMPDIR" ]; then
 	echo "error: could not create temp dir." 1>&2
 	exit 1
 fi
@@ -34,21 +34,26 @@ if [ $? -ne 0 ]; then
 fi
 
 echo "debug: converting PPM files to PDF..." 1>&2
+PDFS=()
 for F in *.ppm; do
-	gm convert $F pdf:$F.pdf
+	gm convert "$F" "pdf:$F.pdf"
 	if [ $? -ne 0 ]; then
-		echo "error: could not convert $F" 1>&2
-		EXIT=1
+		echo "warning: could not convert \"$F\"" 1>&2
 	else
-		PDFS="$PDFS $F.pdf"
+		PDFS+=("$F.pdf")
 	fi
 done
 
 #ls $PDFS 1>&2
 
+if [ "${#PDFS[*]}" -eq 0 ]; then
+	echo "error: no resulting PDF documents. aborting." 1>&2
+	exit 1
+fi
+
 echo "debug: merging PDF files..." 1>&2
-pdfunite $PDFS out.pdf
-if [ $? -eq 0 -a -f out.pdf ]; then
+pdfunite "${PDFS[@]}" out.pdf
+if [ $? -eq 0 ] && [ -f out.pdf ]; then
 	cat out.pdf
 else
 	echo "error: could not merge PDF pages. aborting." 1>&2
